"""update

Revision ID: d4eba5ccb934
Revises: 9ce609e5ef7e
Create Date: 2023-10-27 04:21:29.167596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4eba5ccb934'
down_revision: Union[str, None] = '9ce609e5ef7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laboratory_test', sa.Column('suika_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laboratory_test', 'suika_score')
    # ### end Alembic commands ###
