"""update

Revision ID: 84b94b697e8b
Revises: fc5709aa7470
Create Date: 2023-10-27 04:27:17.157088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b94b697e8b'
down_revision: Union[str, None] = 'fc5709aa7470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laboratory_test', sa.Column('tetris_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laboratory_test', 'tetris_score')
    # ### end Alembic commands ###
